[package]
name = "resume-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.5.3"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
colored = "2.0.4"
